--- 
clone: 
  depth: 1
kind: pipeline
name : OldCam
version: Nexus-sweet
steps:
 - name: Nexus
   image: panchajanya1999/archlinux:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - bash build.sh --proton --lld
